name: CDZtesting
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25056
title: CDZtesting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1f1a17'
    - '#dd127b'
    - '#757472'
    - '#d6d5d3'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 1
purpose: []
